config/routes.rb
Rails.application.routes.draw do
  get 'fake_payment_processor/show'

  devise_for :users
  root to: "dashboard#index"

  # These supercede other /customers routes, so must
  # come before resource :customers
  get "customers/ng", to: "customers#ng"
  get "customers/ng/*angular_route", to: "customers#ng"

  resources :customers, only: [:index, :show, :update]
  get "angular_test" => "angular_test#index"
  get "credit_card_info/:id", to: "fake_payment_processor#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag *webpack_asset_paths("application") %>

    <% if @base_url %>
      <base href="<%= @base_url %>">
    <% end %>
  </head>

  <body class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <%= link_to "Home", root_path, class: "navbar-brand" %>
           <%= link_to "Customers", customers_path, class: "navbar-brand" %>
         </div>

      </div><!-- /.container-fluid -->
    </nav>



    <% if notice.present? %>
      <aside class="alert alert-info">
        <%= notice %>
      </aside>
    <% end %>
    <% if alert.present? %>
      <aside class="alert alert-danger">
        <%= alert %>
      </aside>
    <% end %>
    <%= yield %>
  </body>
</html>